FROM node
WORKDIR /usr/app
COPY . .
RUN yarn
RUN npm run build:server
RUN rm ./packages/server/dist/**/*.d.ts

ENV NODE_ENV=production
EXPOSE 4000
CMD cd ./packages/server && node ./dist/index.js
USER node